language: python

python:
- '2.7'

env:
  global:
    - export NUPIC=$TRAVIS_BUILD_DIR


install:
# Install NuPIC from archive.
- NUPIC_SHA=`cat ci/nupic_sha.txt`
- "echo NUPIC SHA: $NUPIC_SHA"
- python ci/install_from_archive.py
- travis_retry pip install -q -r nupic-linux64-${NUPIC_SHA}/requirements.txt
- export NTA=`pwd`/nupic-linux64-$NUPIC_SHA
- export NTA_CONF_PATH=$TRAVIS_BUILD_DIR/conf
- export PYTHONPATH=$PYTHONPATH:$NTA/lib/python2.7/site-packages
# Install pycept dependency
- pip install pycept

script:
- nosetests
# - nosetests --with-coverage

# after_success:
# - pip install python-coveralls
# - coveralls
